### ISSUE TITLE
Unsafe accesses to storage hitting security issues

### ISSUE THREAD

**Issue by SNikon** [Accedo-Products/appgrid-sdk-js#7]
Hi.

Currently there are accesses to localStorage / sessionStorage which aren't handled for exceptions. Unfortunately several browsers allow forbidding access to storage, namely for private browsing (See Safari in private browsing to hit issue "QuotaExceededError (DOM Exception 22)" when storing deviceId).

A solution for this is to wrap ALL accesses to storage with try catch and on hitting an exception disabling "hasSomeWebStorage" variable and using a variable in memory as storage instead. As this issue was seemingly never hit, it seems that if the browser does not support localStorage and sessionStorage then appgrid does not fallback to memory and that is not correct as we can no longer provide a deviceId to the backend.

Best Regards

**Comment by gouegd** [comment]
Hi @SNikon,
Thank you for reporting this issue !
After a few tests it seems the error does not occur when accessing either webstorage, but only when trying to actually store something, in incognito mode. The same could happen if the storage was, indeed, full (in normal browsing mode).

It was a good suggestion but don't need to use an in-memory persistency strategy because the deviceId and sessionKey are already stored in-memory, in each appgrid client instance. The persistency layer is only read once (at startup) and written anytime needed.

It's possible to define your own functions to decide on how to handle persistency, so that you could go around this issue, but I agree the SDK should handle it itself in this case. We're looking at this and will release a patch very soon.
Thanks again !

**Comment by gouegd** [comment]
This is now fixed and released in v3.2.2.
As can be expected, in incognito mode, by default there will be no persistency on local/sessionStorage (because it will silently fail now).
If desired, a different behaviour could be coded via the `onSessionKeyChanged`, `onDeviceIdGenerated` and `browserInfoProvider` options.
